name: flutter_engineer_codecheck
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  device_preview:
  flutter_riverpod:
  http:
  convert:
  go_router:
  intl:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^2.3.13
  flutter_test:
    sdk: flutter

  flutter_lints:
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true  
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/ios_appicon.png"
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#6eb8bb"
  adaptive_icon_foreground: "assets/android_appicon.png"

flutter_native_splash:
  color: "#6eb8bb"
  image: assets/splash.png
  android_12:
    image: assets/splash_android.png
    color: "#6eb8bb"