name: flutter_engineer_codecheck
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  device_preview:
  flutter_riverpod:
  http:
  convert:
  go_router:
  intl:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true  
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ios_appicon.png"